version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/mydatabase.db:/app/mydatabase.db
  frontend:
    build: ./frontend
    ports:
      - "80:80"